# Default values for kanbanboard-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ingress:
  enabled: false


backend:
  
  name: kanban-app
  image:
    repository: sdandey/dandey-apps:kanban-board-kanban-app
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
  
  env:
    - name: DB_SERVER
      value: kanban-postgres
    - name: POSTGRES_DB
      value: kanban
    - name: POSTGRES_PASSWORD
      value: kanban
    - name: POSTGRES_USER
      value: kanban
  
  resources: 
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi

  ports:
    containerPort: 8080
    targetPort: 8080
  
  service:
    type: NodePort

serviceAccount:
  backend: 
    create: false
    annotations: {}
    name: "default"
  frontend:
    create: false
    annotations: {}
    name: "default"



service:
  type: ClusterIP
  port: 80



autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
